---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Release.Name }}-filebrowser-quantum-data
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.dataSize }}
  storageClassName: {{ .Values.persistence.storageClass }}
---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: {{ .Release.Name }}-filebrowser-quantum-config
  labels:
    release: {{ .Release.Name }}
    app: filebrowser-quantum
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.configSize }}
  storageClassName: {{ .Values.persistence.storageClass }}  
{{- end }}
